final url = 'http://192.168.1.10:3000/';
final registeration = url + "registeration";
final login = url + "login";
final create_trip = url + "create_trip";
final driver_trips =url + "driver_trips";
final delete_trip = url + "delete_trip";
final all_trip = url + "all_trip";
final filtered_trips = url + "filtered_trips";
final book_trip = url + "book_trip";