// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCofdbZo-cMsVnyLJjdLpVp2nICnQlADrQ',
    appId: '1:48327304223:web:e7e712df2a055e6c33612a',
    messagingSenderId: '48327304223',
    projectId: 'project1-c2e5a',
    authDomain: 'project1-c2e5a.firebaseapp.com',
    storageBucket: 'project1-c2e5a.firebasestorage.app',
    measurementId: 'G-SJCV9545W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOycBjuMPb3XJ67H0BygHWjDke7cBOz6I',
    appId: '1:48327304223:android:338e426a4420722233612a',
    messagingSenderId: '48327304223',
    projectId: 'project1-c2e5a',
    storageBucket: 'project1-c2e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEX29gd2f5dJJRyNrF8DzcEdbv6L0GAq4',
    appId: '1:48327304223:ios:5862686bb960822a33612a',
    messagingSenderId: '48327304223',
    projectId: 'project1-c2e5a',
    storageBucket: 'project1-c2e5a.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCofdbZo-cMsVnyLJjdLpVp2nICnQlADrQ',
    appId: '1:48327304223:web:d72a986e6265c80d33612a',
    messagingSenderId: '48327304223',
    projectId: 'project1-c2e5a',
    authDomain: 'project1-c2e5a.firebaseapp.com',
    storageBucket: 'project1-c2e5a.firebasestorage.app',
    measurementId: 'G-95B7KNEER7',
  );
}
